name: Create PR From dev To main
on:
  push:
    branches:
      - dev
jobs:
  create_pr_dev_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sudo env UV_INSTALL_DIR="/usr/local/bin" sh
      - name: Create PR From dev To main
        run: | 
          curl -sSL https://raw.githubusercontent.com/legendu-net/github_actions_scripts/main/create_pull_request.py \
            | uv run --script - \
            --head-branch dev \
            --base-branch main \
            --token ${{ secrets.GITHUBACTIONS }}

