name: Update JupyterLab Version
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  update-jupyterlab-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Run Python Script
        run: |
          curl -sSL https://raw.githubusercontent.com/legendu-net/github_actions_scripts/main/update_version_dockerfile.py \
            | uv run --script - \
            --repo jupyterlab/jupyterlab \
            --token ${{ secrets.GITHUBACTIONS }}

